title: Platformer 4.0
description: "Winter 2025"
owner_name: Nighthawk Coding 
github_username: nighthawkcoders
github_repo: "platformer4x"
baseurl: "/platformer4x"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders/platformer4x"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }      
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/search.md
  - navigation/about.md
